"""add customer.location

Revision ID: 008fe2f3ad80
Revises: 
Create Date: 2025-10-06 09:40:01.724075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008fe2f3ad80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
